Adding delete + labels modals to vmi list
kubevirt-ui/kubevirt-plugin pull request #206
Opened 2022-04-03 10:05 UTC by metalice

## 📝 Description

> Add a brief description

## 🎥 Demo

<img width="943" alt="image" src="https://user-images.githubusercontent.com/14824964/161422311-2cd35b00-eee2-412c-9924-f6ddde201984.png">

<img width="894" alt="image" src="https://user-images.githubusercontent.com/14824964/161422329-b1231c78-1a1a-4bbd-9d56-e160e1f98488.png">

2022-04-03 17:34 UTC, metalice commented
/retest

2022-04-04 18:04 UTC, hstastna requested changes
All the labels in the Kebab menu won't be translated like this. I'd suggest to add the `t` function to all of them:
![translate](https://user-images.githubusercontent.com/13417815/161602124-4d16d3f0-f78f-4716-b35f-be9b01e262f0.png)

The modal for editing labels could work a bit better. I have to click on _Submit_ button twice (or somewhere else in the screen for the first time), when adding/editing some label, it's annoying. It also adds an unnecessary empty line, when clicking on Submit (or anywhere else) for the first time. When removing some label or canceling this action, I have to click on Submit only once. I'd suggest to look into the implementation of _LabelsModal_ you use here. Maybe we can do something about that, maybe not, I'm not sure.
![hello](https://user-images.githubusercontent.com/13417815/161603867-e2fae793-cc3d-46e2-9efb-0edf3599f323.png)

Otherwise the code looks great and deleting VMIs or editing their labels works! 👍🏽

2022-04-05 05:42 UTC, metalice commented on src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
>          label: 'Edit Labels',
great comment!

2022-04-05 05:44 UTC, metalice commented on src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
> +          // createModal(({ isOpen, onClose }) => (
indeed this PR was waited for the annotation label to be merged first and this is why it's in the comment. now when the annotation modal has been merged this pr can be edited and merged.

2022-04-05 05:45 UTC, metalice commented
> All the labels in the Kebab menu won't be translated like this. I'd suggest to add the `t` function to all of them: ![translate](https://user-images.githubusercontent.com/13417815/161602124-4d16d3f0-f78f-4716-b35f-be9b01e262f0.png)
> 
> The modal for editing labels could work a bit better. I have to click on _Submit_ button twice (or somewhere else in the screen for the first time), when adding/editing some label, it's annoying. It also adds an unnecessary empty line, when clicking on Submit (or anywhere else) for the first time. When removing some label or canceling this action, I have to click on Submit only once. I'd suggest to look into the implementation of _LabelsModal_ you use here. Maybe we can do something about that, maybe not, I'm not sure. ![hello](https://user-images.githubusercontent.com/13417815/161603867-e2fae793-cc3d-46e2-9efb-0edf3599f323.png)
> 
> Otherwise the code looks great and deleting VMIs or editing their labels works! 👍🏽

This PR didn't create the modals only consumed them, if those modals act "weird" we should tackle it, but in a follow-up PR. Thank you for bringing it to my attention.

2022-04-05 06:58 UTC, glekner commented
/lgtm

2022-04-05 09:15 UTC, merged