Bug 2140977: Display correct number of Alerts on Overview page
kubevirt-ui/kubevirt-plugin pull request #975
Opened 2022-11-18 19:07 UTC by hstastna

## 📝 Description

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2140977

Display the correct total number of Alerts on Virtualization _Overview_ page - _Alerts_ card, according to the selected scope:
- Virtualization health only or
- All alerts.

## 🎥 Screenshots
**Before:**
Number of all alerts displayed in the brackets, when "Show virtualization health alerts" selected:
![virt_before](https://user-images.githubusercontent.com/13417815/202782874-042fec7f-1981-4632-a6de-769a2d2142c0.png)
**After:**
Only the number of virtualization health alerts displayed:
![virt_after](https://user-images.githubusercontent.com/13417815/202782891-9def0082-4017-4cb2-9b80-13783d9bec19.png)

2022-11-18 19:10 UTC, hstastna commented
@avivtur @metalice @pcbailey @yzamir @vojtechszocs please review

2022-11-18 21:03 UTC, pcbailey commented
/lgtm

2022-11-20 09:47 UTC, avivtur requested changes
/hold
if this PR hasn't been merged into the main branch yet, you need to close this PR, 
open it for the main branch and then backport it.

2022-11-20 23:32 UTC, hstastna commented
@avivtur I know but if you check the bugzilla comments, you will find Tal has changed the target release from 4.13.0 to 4.12.0, just a few days ago. I believe he knows what he is doing...

2022-11-21 08:56 UTC, avivtur commented
> @avivtur I know but if you check the bugzilla comments, you will find Tal changed the target release from 4.13.0 to 4.12.0, just a few days ago. I believe he knows what he is doing...

I assume he made that target release change before we created a new release for 4.12, 
now as we are after release, we need to re-target your BZ to 4.13, clone a new BZ for 4.12, merge this PR for 4.13, and than backport it to 4.12

2022-11-21 13:21 UTC, hstastna commented
> We have branched out to a new version on the 16th and the bug shifted target on the 15th.
Either way, this bug should be added to main and then cherry picked :) if you need any help let me know

@metalice are you saying the BZ was probably moved to 4.12 by mistake? @tnisan WDYT? Thanks.

2022-11-21 13:28 UTC, pcbailey commented
Aviv and Matan are correct. I didn't notice that it was targeted to 4.12. If a PR isn't created for main the code will be missing from 4.13. If you go ahead and make the PR for main we can get both merged before Tal gets back from PTO.

2022-11-22 18:09 UTC, pcbailey commented
/lgtm

2022-11-23 13:23 UTC, hstastna commented
/hold cancel

2022-11-23 13:28 UTC, merged